### ISSUE TITLE
create does not appear to be published yet

### ISSUE THREAD

**Issue by uglyoldbob** [HadrienG2/hwlocality#25]
I don't see a hwlocality crate on crates.io.

**Comment by HadrienG2** [comment]
Indeed, there are a few code review / quality things I'd like to finish before the first official release : more unit tests, more examples, ensure all the right traits are implemented for public types, etc.

For the time being, my own projects use a git dependency, but if you can't wait, I can consider a 0.1 release as an alternative.

**Comment by uglyoldbob** [comment]
Using it as a git dependency is fine for now. I put together a pull request on a different feature for the repo

**Comment by HadrienG2** [comment]
@uulm-janbaudisch It's not fully clear to me what you have in mind, but wouldn't it help more if I followed the example of other projects and extracted an `hwlocality-sys` subcrate that does just the version detection, linking, and C API entry points? Because while the idiomatic Rust layer needs a bit more polish/cleanup work, a raw C API binding should be doable in a couple days.

**Comment by uulm-janbaudisch** [comment]
Yes, a `sys` crate would be great. To make it simpler, would using `bindgen` be possible? If I am not mistaken, `src/ffi.rs` seems to be created by hand, right?

**Comment by HadrienG2** [comment]
Indeed, `src/ffi.rs` is written by hand. There are quite a few reasons why I didn't want to use bindgen:

1. Like all automated binding generation tools, bindgen produces the kind of unreadable and undocumented code that I hate having to deal with (and would not want to force on anyone else).
2. Because C enums have ambiguous semantics (they can be used to model closed and open sets, true enums and bitfields...), a manual binding can have clearer semantics than an automatically generated one. Bindgen acknowledges this by letting you feed a bunch of regexes to switch between various enum translation styles, but if you're doing that, you're bringing manual binding work back, and regexes on open sets are fragile...
3. bindgen doesn't stop at hwloc entry points only but produces an enormous amount of irrelevant junk (basically a copy of every compiler define and every libc header that's transitively included by hwloc.h).
4. The recommended workflow of adding bindgen to build.rs means making every build requires libclang, which in turn means bothering my users with one more C dependency.
    - The common workaround of pre-baking the binding through a local bindgen-cli run will not work with hwloc because it has a fair number of few version- and OS-dependent entry points, which would require equivalently many adjustements to the automatically generated bindgen output, defeating the point of automatic generation.
5. The main benefit that I _should_ get in exchange of all these drawbacks of autogenerated bindings is easy adaptation to upstream changes. Except hwloc is a mature library, so changes are rare and small. Therefore, this is not a strong benefit.
6. hwloc type naming choices are frankly awful, using nicer names internally was a big readability improvement.
7. Like all C library documentations, hwloc documentation sucks at articulating safety invariants. If I own the type definitions, [I can document them on my side](https://github.com/HadrienG2/hwlocality/blob/lints/src/object/mod.rs#L1039), setting conservative assumptions where needed.
8. Owning the type definition also allowed me to avoid duplication between the "raw type" and the "high level type" in some cases, where I can just have a high level type with hidden fields.

Of course, in the process of creating a `-sys` crate that mimicks the API of the C API, benefits 6-8 will have to go. But I still think that benefits 1-5 were worth the work of writing a manual binding.

**Comment by HadrienG2** [comment]
@uulm-janbaudisch There you go: https://crates.io/crates/hwlocality-sys.

**Comment by uulm-janbaudisch** [comment]
@HadrienG2 Thank you!

**Comment by nazar-pc** [comment]
BTW it is possible to release alpha and beta versions to crates.io and they will be considered experimental and not stable. Versioning around them is a bit tricky, but with lock file should be fine to use.

**Comment by HadrienG2** [comment]
Thanks @nazar-pc, I forgot about this possibility, and it seems like a good fit for the need expressed by you and @uglyoldbob.

Although I've been making some major progress with improving test coverage in the past months, some major functionality like cpu/memory binding is still completely untested, which is why I would be a little uncomfortable tagging this as even a 0.1 release for now.

But 0.1alpha1 sounds like the right way to tell my prospective users the intended message: "mostly feature complete, feel free to play around and submit feedback, but proceed with care as some stuff may still be broken and I may need to break the API to fix it".

And after all, my test coverage is public on codecov, so people can easily get an overview of what is covered by tests and what isn't covered yet.
